language: ruby
rvm:
  - 1.9.2
  - 2.0.0
before_script:
  - rake travis:setup
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  
env:
  - CI_REPORTS=shippable/testresults COVERAGE_REPORTS=shippable/codecoverage

notifications:
  email: 
    - vidya@shippable.com
